version: '3.8'
services:
  upbit_order_book_fetcher:
    container_name: upbit_order_book_fetcher
    # restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: fetcher
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: host
    environment:
      - TZ=UTC